### ISSUE TITLE
Incorrect dihedral type when the structure contains three-membered ring

### ISSUE THREAD

**Issue by xu139411** [akohlmey/topotools#17]
When the structure has a three-membered ring (e.g., an epoxide group), TopoTools will create an incorrect type of dihedral in which the first and last atom are the same.

How to reproduce this error:
1) Open VMD 1.9.3 and then the TK console. Load the data:
*topo readlammpsdata pGO.data full*

The data file is a graphene oxide with epoxides and hydroxyls on its surface. The atom type and bond type is based on (https://doi.org/10.1016/j.commatsci.2015.12.030).

2) Generate angles and dihedrals
*topo guessangles*
*topo guessdihedrals*

3) Export the data:
*topo writelammpsdata pGO_with_angle_dihedral.data full*

In the generated data file, **dihedral type 24** is the incorrect dihedral type. An example is dihedral 63: **63 24 162 7 8 162**.

TopoTools has helped my research a lot. Thanks for providing such a tool!
 
[datafile.zip](https://github.com/akohlmey/topotools/files/3877957/datafile.zip)

**Comment by akohlmey** [comment]
Thanks for reporting. This should be fixed with commit 0bc3951f707420a2651b403ce8eddc6c7dfbaa57
Please download a copy of the latest plugin from https://github.com/akohlmey/topotools/archive/master.zip, create a folder topotools1.8 next to the existing topotools1.7 folder of your VMD installation and copy all the .tcl files there.
You can test, if this worked in the VMD console:
```
vmd > package require topotools
1.8
vmd > 
```
If it shows 1.7, the installation of the update package failed.

**Comment by xu139411** [comment]
This is to confirm that commit 0bc3951 fixes the problem after testing on the original graphene oxide structure as well as a larger one.

Thanks!

**Comment by akohlmey** [comment]
issue is resolved with the latest changes. They will be included in VMD after a few more other changes are completed.
